<?php

/**
 * @file
 * Functions to support theming in the Specbee theme.
 */

/**
 * Implements hook_preprocess_page() for Page document templates.
 */
function specbee_preprocess_block(&$variables) {
  if ($variables['elements']['#derivative_plugin_id'] == 'card') {
    $variables['image_alignment'] = $variables['elements']['content']['#block_content']->get('field_image_alignment')->getvalue()[0]['value'];
  }
}
